apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: adarshsavaligi/testing:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_PASSWORD
          value: mysecretpassword
        - name: DATABASE_NAME
          value: mydatabase
        - name: DATABASE_HOST
          value: postgresql-service
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007
  type: NodePort
